### ISSUE TITLE
Screen does not always respond to pressing

### ISSUE THREAD

**Issue by Nidrop** [cryptomilk/android_device_sony_lilac#52]
I used a calculator to determine the conditions when a problem occurs.
If you enter the numbers very quickly, then everything works fine. But if you wait 1-2 seconds between clicks, then in this case some clicks can be ignored.

This guy attach log if it can help: [xda post](https://forum.xda-developers.com/xperia-xz1-compact/development/rom-lineageos-16-0-unofficial-todo-t3925675/post80732369#post80732369)
Screen protection does not affect the problem. 
My update path: 47.2.A.11.228 -> LOS 16 1.0 -> LOS 16 1.2

**Comment by foresto** [comment]
I'm experiencing the same problem with the lineage-17.1 branch, also coming from stock 47.2.A.11.228 and extracting vendor blobs from the same stock version (except for those that are pinned by this project)

 I haven't noticed anything obviously helpful in the logs yet, but I'm happy to answer questions.

**Comment by foresto** [comment]
I did some experiments, and noticed a few things about the lost touch events:

* It happens less frequently with Settings: Sound: Advanced: Touch Sounds: on.
* It happens less frequently with Settings: Battery: Battery Saver: Performance Profile: Performance.
* It never happens while charging.
* Enabling Developer Options: Input: Show Taps makes it easier to notice, because a visual indicator appears for every detected tap, regardless of what is on that area of the screen.
* I can reproduce the problem on builds from cryptomilk's sources, with both the lineage-17.1 branch and the lineage-16.0 branch. (Tested using the lineage-17.1 kernel in both cases, using `lunch lineage_lilac-userdebug`.)
* I could not reproduce the problem with stock firmware.

I found it interesting to see the problem reduced by touch sounds, so I ran `top` while tapping calculator buttons with touch sounds enabled, and noticed the `audioserver` process using significant CPU time for a second or two upon each tap. Perhaps the increased CPU load reduces the failure rate?

**Hypothesis:**
The lost tap events could be caused by a power saving feature, perhaps interfering with either the touch sensor or the process/driver that monitors it. This could explain why it happens less often in Performance mode and not at all while charging. (Power saving measures are probably less aggressive in those states.) It could also explain why touch sounds affect the problem: Since each tap triggers audioserver CPU load, that load might prevent the system from entering a problematic power saving state.

**Open Questions:**
* How does cryptomilk's lineage-17.1 kernel differ from the stock kernel? (Task scheduler, IO scheduler, blob versions, CONFIG_HZ, etc.)
* Does cryptomilk's lineage-16.0 kernel behave any differently?
* Does building with `lunch lineage_lilac-eng` or `lineage_lilac-user` help?

**Comment by derfelot** [comment]
Hi there,

thanks for the reports.

> **Open Questions:**
> 
>     * How does cryptomilk's lineage-17.1 kernel differ from the stock kernel? (Task scheduler, IO scheduler, blob versions, CONFIG_HZ, etc.)

In the end, quite significantly. We are using a completely different CAF base (in the case of los 17.1 anyway), plus a lot of other modifications (e.g. to enable building wit clang, enabling vDSO, etc).

>     * Does cryptomilk's lineage-16.0 kernel behave any differently?

I would guess not, the only difference is the CAF base. All the other modifications mentioned above were also applied there.

>     * Do cryptomilk's pinned blobs affect it?

That shouldn't be the case, as they only relate to camera libraries, display and stock audio hal from the top of my head.

>     * Does building with `lunch lineage_lilac-eng` or `lineage_lilac-user` affect it?

I wouldn't recommend building engineering builds these days anymore. From what I remember from a discussion on the LOS slack, nobody really takes care anymore to see if it actually still works. I remember doing so on 16.0 and it completely broke sth related to the modem-switcher (most likely), requiring me to flash stock again to fix my modem.

Here is a list of commits you can try to revert in the 17.1 kernel, which are more likely have an impact on the issue described here than others:

https://github.com/derfelot/android_kernel_sony_msm8998/commit/c046d44c38f1bce89745c56c6c418172f12e7edc
https://github.com/derfelot/android_kernel_sony_msm8998/commit/67a9a5ccb3e2d5e688550c015d18a9e6a409e93b
https://github.com/derfelot/android_kernel_sony_msm8998/commit/67628b4deb847b1b50614f5a096da1195edf25f5
https://github.com/derfelot/android_kernel_sony_msm8998/commit/edd8e3533b58956582aaee2a77dfd8c3e67d8961
https://github.com/derfelot/android_kernel_sony_msm8998/commit/9232b13736e49b7c8b68e70e9fb1c6801e7f38ce
https://github.com/derfelot/android_kernel_sony_msm8998/commit/4453e0345b5c8fe4ebb96c9ecad8f79bd9562ae4
https://github.com/derfelot/android_kernel_sony_msm8998/commit/8e960fe1b7b0b35b98360eec37643fd7ee7133bd
https://github.com/derfelot/android_kernel_sony_msm8998/commit/879a639a234d9a09680d8dd8a1e711d44bdced2a
https://github.com/derfelot/android_kernel_sony_msm8998/commit/d3b0cf487167b72c3e2c6de717b1c55122e5b0f0
https://github.com/derfelot/android_kernel_sony_msm8998/commit/8a7c0f97845f8ae9b44ce9178c939040177d1d9d
https://github.com/derfelot/android_kernel_sony_msm8998/commit/f9f72d836b8878c88a18455447f145acc93e535c
https://github.com/derfelot/android_kernel_sony_msm8998/commit/337b01f0809a1080c9d2b71e7bee7d63a70c1e6d
https://github.com/derfelot/android_kernel_sony_msm8998/commit/84c7bb4f76279685b05523e0040297f6fa9b82fa
https://github.com/derfelot/android_kernel_sony_msm8998/commit/18dce637e60bb981a8644f2ac59686db250f6b21

**Comment by derfelot** [comment]
This has now moved to 

https://github.com/whatawurst/android_device_sony_yoshino/issues/2
